# Site settings
title: Pradeep's Photo Gallery
description: "" #Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/pictures" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://ppf2002.github.io/pictures/
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ppf2u

# Build settings
markdown: kramdown
